spring:
  application:
    name: empleados-app

  datasource:
    url: jdbc:mysql://localhost:3306/employees
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: benjamin
    password: cdas9238rncdsa!

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

jwt:
  secret-key: 0Uk4tgIWwpXKSB8VFTZ9qtVhTawFt5eOrQrOJEbvjdd3LYzRUPs49O0vdEeAP2RYlVCDd6zjBEpiX9HsQN0YFQ==
  expiration-time-access-token: 600
  expiration-time-refresh-token: 3600


