spring:
  application:
    name: empleados-app

  datasource:
    url: ${URL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_DB}
    password: ${PASS_BD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

jwt:
  secret-key: 0Uk4tgIWwpXKSB8VFTZ9qtVhTawFt5eOrQrOJEbvjdd3LYzRUPs49O0vdEeAP2RYlVCDd6zjBEpiX9HsQN0YFQ==
  expiration-time-access-token: 600
  expiration-time-refresh-token: 3600
